on: [push, pull_request]

permissions:
  contents: read

jobs:
  lint-black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
      - run: uv run black --check --diff handtokening/

  lint-ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
      - run: uv run ruff check handtokening/

  test:
    runs-on: ubuntu-latest
    env:
      CLAMSCAN_PATH: /usr/bin/true
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
      - name: Install dependencies
        run: sudo apt update && sudo apt install -y osslsigncode
      - run: uv run manage.py test
